version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: vk_deadline_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vk_deadline
      POSTGRES_USER: vk_deadline
      POSTGRES_PASSWORD: vk_deadline
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: